name: Auto ZIP to Telegram

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build zip
        run: |
          zip -r alex_notify_build.zip . -x ".git/*" ".github/*" "__pycache__/*"

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: alex_notify_build.zip

      - name: Notify bot
        run: |
          curl -sS -X POST "${{ secrets.RAILWAY_URL }}/api/push?token=${{ secrets.SECRET_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"url\":\"https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/alex_notify_build.zip\"}"
